install.packages("sqldf")
library(sqldf)
myFile <- "household_power_consumption.txt"
mySql <- "SELECT * from file WHERE Date = '1/2/2007' OR Date = '2/2/2007'"
power<- read.csv.sql(myFile, sql=mySql, sep=";")
power$newDate<-paste(power$Date,power$Time)
power$newDate<-strptime(power$newDate,"%d/%m/%Y %H:%M:%S")
par(mfcol=c(2,2))
plot(power$newDate, power$Global_active_power, type="l", ylab="Global Active Power (Kilowatts)", xlab="")
plot(power$newDate, power$Sub_metering_1, type="n",xlab="", ylab="Energy sub metering")
points(power$newDate, power$Sub_metering_1, type="l", col="black")
points(power$newDate, power$Sub_metering_2, type="l", col="red")
points(power$newDate, power$Sub_metering_3, type="l", col="blue")
legend("topright",pch="___",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(power$newDate, power$Voltage, type="l",xlab="datetime", ylab="Voltage")
plot(power$newDate, power$Global_reactive_power, type="l",xlab="datetime", ylab="Global_reactive_power")
dev.copy(png,file="plot4.png")
dev.off()
